name: Build and Push to ACR

on:
  push:
    branches:
      - 'master'

env:
  AZURE_CONTAINER_REGISTRY: "acrdeel"
  RESOURCE_GROUP: "rg-honest-hog"
  CLUSTER_NAME: "cluster-mutual-yeti"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      pages: write
        
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image acrdeel.azurecr.io/abiola89/deel:{{.Run.ID}} -r acrdeel -g rg-honest-hog .
